### ISSUE TITLE
想问一下，release的几个uboot都分别是干啥的

### ISSUE THREAD

**Issue by weigeloveu** [hzyitc/u-boot-onecloud#1]
eMMC.burn.img，这个是直接把固件写进emmc吗？我刷的这个底包，还是启动了u盘上的系统，并且没有把系统写进emmc
u-boot.bin这个跟emmcburn有啥区别呢

**Comment by hzyitc** [comment]
`release`里面包含了各个阶段的文件：`SPL`，`u-boot`，压缩后的`u-boot`，组合后的`u-boot`，图片资源包，直刷包。
