### ISSUE TITLE
在引导时按什么按键可以进入命令行？

### ISSUE THREAD

**Issue by liushengxin** [hzyitc/u-boot-onecloud#11]
引导时一般按某个按键可进入命令，但是不知道具体什么按键？

因为密码忘了，想进入命令行passwd修改。

不知道按什么按键能进入命令行，尝试了‘space’、‘s’、‘d’、‘ctrl+Z/C’ 都无效。

我的镜像是`Armbian_23.08.0-trunk_Onecloud_bookworm_current_6.1.32.burn`，拜托💖HZ大佬 @hzyitc

**Comment by lanlanpy** [comment]
可以优盘写个大佬的镜像启动，然后挂载emmc的p2分区
替换etc目录下的shadow文件

**Comment by liushengxin** [comment]
> 可以优盘写个大佬的镜像启动，然后挂载emmc的p2分区 替换etc目录下的shadow文件

非常感谢蓝蓝。已经按照您的方法恢复啦。😘😘😘😘😘

**Comment by hzyitc** [comment]
你说的那个是grub。

uboot下直接配置cmdline进入单用户模式就行。
