### ISSUE TITLE
最新版本 build-20221028-0940 无法刷入

### ISSUE THREAD

**Issue by qianxuu** [hzyitc/u-boot-onecloud#4]
上一版正常
![image](https://user-images.githubusercontent.com/62287903/198867619-513b45c9-4506-44f9-a028-97e598a2a937.png)

**Comment by qianxuu** [comment]
另外想知道 armbian-onecloud 那边 CI 如何修改可以指定 uboot 版本，我把这行`UBOOT_RELEASE: `从`latest`改成 `build-20221017-1550`并不行
![image](https://user-images.githubusercontent.com/62287903/198867766-1df2677e-1264-4b2f-b9fe-c9c9af388269.png)

**Comment by xuexijiaoben** [comment]
能刷入

**Comment by hzyitc** [comment]
看下TTL那边提示什么错误吧。

CI那边确实是个问题。当时没仔细看API手册。用的这个API需要指定的是release的id而不是tag。

**Comment by hzyitc** [comment]
看下TTL那边提示什么错误吧。

CI那边确实是个问题。当时没仔细看API手册。用的这个API需要指定的是release的id而不是tag。

**Comment by qianxuu** [comment]
> 看下TTL那边提示什么错误吧。
> 
> CI那边确实是个问题。当时没仔细看API手册。用的这个API需要指定的是release的id而不是tag。

烦请指导如何查看 TTL 的错误

**Comment by lanlanpy** [comment]
> > 看下TTL那边提示什么错误吧。
> > CI那边确实是个问题。当时没仔细看API手册。用的这个API需要指定的是release的id而不是tag。
> 
> 烦请指导如何查看 TTL 的错误

V1.3主板 短接那个位置旁边有ttl接口，tx rx gnd vcc那里，买个ttl转usb模块接上用串口调试工具就可以看上电后主板的启动信息

**Comment by lanlanpy** [comment]
> > 看下TTL那边提示什么错误吧。
> > CI那边确实是个问题。当时没仔细看API手册。用的这个API需要指定的是release的id而不是tag。
> 
> 烦请指导如何查看 TTL 的错误

哥们要来QQ群组织交流吗 612500698，加群备注一下你GitHub名字。我是管理
