### ISSUE TITLE
大佬可否考虑加入CONFIG_BOOTDELAY，去掉背景图

### ISSUE THREAD

**Issue by swibkpt** [hzyitc/u-boot-onecloud#9]
延迟3秒再进行autoboot，这样方便调试。
对于能刷机玩armbian的人来说，autoboot的背景图片反而是画蛇添足了，不如boot log看着舒服。

**Comment by hzyitc** [comment]
本来就开着啊，命令行在串口。

这个u-boot并没有把HDMI当成命令行的能力。

**Comment by swibkpt** [comment]
感谢回复。
既然原有版本就不支持，那我也死心了。
